# Generated by Django 2.2.5 on 2019-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='user',
            new_name='planner',
        ),
        migrations.AddField(
            model_name='trip',
            name='buddies',
            field=models.ManyToManyField(related_name='trip', to='python_exam_app.User'),
        ),
    ]
